//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QianShiMusic.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QianShiMusic.Resources.Strings.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your account. 的本地化字符串。
        /// </summary>
        public static string AccountHit {
            get {
                return ResourceManager.GetString("AccountHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account or password can not empty! 的本地化字符串。
        /// </summary>
        public static string AccountOrPasswordCanNotEmpty {
            get {
                return ResourceManager.GetString("AccountOrPasswordCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Friend 的本地化字符串。
        /// </summary>
        public static string AddFriend {
            get {
                return ResourceManager.GetString("AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friend 的本地化字符串。
        /// </summary>
        public static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friend Apply 的本地化字符串。
        /// </summary>
        public static string FriendApply {
            get {
                return ResourceManager.GetString("FriendApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login Successed! 的本地化字符串。
        /// </summary>
        public static string LoginSuccessed {
            get {
                return ResourceManager.GetString("LoginSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Friend 的本地化字符串。
        /// </summary>
        public static string NewFriend {
            get {
                return ResourceManager.GetString("NewFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Sessions 的本地化字符串。
        /// </summary>
        public static string NoSessions {
            get {
                return ResourceManager.GetString("NoSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pass 的本地化字符串。
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your password. 的本地化字符串。
        /// </summary>
        public static string PasswordHit {
            get {
                return ResourceManager.GetString("PasswordHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Account/NickName/GroupNumber 的本地化字符串。
        /// </summary>
        public static string QueryFriend {
            get {
                return ResourceManager.GetString("QueryFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reject 的本地化字符串。
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send success. 的本地化字符串。
        /// </summary>
        public static string SendSuccessed {
            get {
                return ResourceManager.GetString("SendSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter verification information. 的本地化字符串。
        /// </summary>
        public static string VerificationHit {
            get {
                return ResourceManager.GetString("VerificationHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification info can not empty. 的本地化字符串。
        /// </summary>
        public static string VerificationInfoCanNotEmpty {
            get {
                return ResourceManager.GetString("VerificationInfoCanNotEmpty", resourceCulture);
            }
        }
    }
}
